server:
  port: 8081

spring:
  datasource:
    url: ${RP_DB_URL:jdbc:postgresql://localhost:5432/kafka-task}
    username: ${RP_DB_USER:postgres}
    password: ${RP_DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: request_processor
    show-sql: false

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: request_processor

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    admin:
      auto-create: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      acks: all
      retries: 3
      properties:
        enable.idempotence: true

outbox:
  batch-size: 50
  delay-ms: 1000

logging:
  level:
    root: INFO
    org.apache.kafka.clients: WARN
